### PR TITLE
[NeoFrag] add german lang

### PR DESCRIPTION
**Pull request by renegade1337**

### CODE REVIEW

**Comment by michaelbilcot** [comment]
Thank you, it's very helpful for us

**Comment by renegade1337** [comment]
It would be nice if the CMS was completely multilingual.

A crowd integration would be great!

**Comment by renegade1337** [comment]
Is the pull requests also processed?
And can one help with the implementation of multilingualism?

**Comment by DanielK1511** [comment]
@xxxrenegade If i translated it myself, i do a fork or so for the devs to release too!

**Comment by BloberSh** [comment]
Since language system changed, it's now outdated.

**Pull request closed without merging**
